shared_examples 'elasticsearch' do
  describe command('sv status elasticsearch') do
    its(:stdout) { should contain 'run: elasticsearch' }
  end

  describe command('curl http://localhost:9200/') do
    its(:stdout) { should contain '"status" : 200,' }
  end
  describe command('curl -s http://localhost:9200/_cluster/state') do
    its(:stdout) { should contain 'elasticsearch' } # node name
  end

  describe file('/etc/service/elasticsearch/env/ES_USER') do
    it { should be_file }
    its(:content) { should contain 'elasticsearch' }
  end

  describe file('/opt/elasticsearch/elasticsearch-1.7.1/config/elasticsearch.yml') do
    it { should be_file }
    its(:content) { should contain '# This file was generated by Chef' }
  end

  describe file('/opt/elasticsearch/elasticsearch-1.7.1/config/logging.yml') do
    it { should be_file }
    its(:content) { should contain '# This file was generated by Chef' }
  end

  describe file('/var/log/elasticsearch/current') do
    it { should be_file }
    its(:content) { should contain 'bound_address' }
  end
end
