# sshd_service = os[:family] == 'redhat' ? 'sshd' : 'ssh'

shared_examples 'elasticsearch' do
  describe command('sv status elasticsearch') do
    its(:stdout) { should match 'run: elasticsearch' }
  end

  # TODO: unreliable
  # describe command('curl http://localhost:9200/') do
  #   its(:stdout) { should match '"status" : 200,' }
  # end
  # describe command('curl http://localhost:9200/_cat/health') do
  #   its(:stdout) { should match 'elasticsearch' } # node name 
  # end

  describe file('/etc/service/elasticsearch/env/ES_USER') do
    it { should be_file }
    its(:content) { should match 'elasticsearch' }
  end

  describe file('/opt/elasticsearch/elasticsearch-1.7.0/config/elasticsearch.yml') do
    it { should be_file }
    its(:content) { should match '# This file was generated by Chef' }
  end

  describe file('/opt/elasticsearch/elasticsearch-1.7.0/config/logging.yml') do
    it { should be_file }
    its(:content) { should match '# This file was generated by Chef' }
  end

end
