shared_examples 'kibana' do
  describe command('sv status kibana') do
    its(:stdout) { should contain 'run: kibana' }
  end
  describe file('/opt/kibana/kibana-4.1.1/config/kibana.yml') do
    it { should be_file }
    its(:content) { should contain '# This file was generated by Chef' }
  end
  describe command('curl http://localhost:8080') do
    its(:stdout) { should contain 'Kibana 4' }
  end
  describe file('/var/log/kibana/current') do
    it { should be_file }
    its(:content) { should contain 'Listening on 0.0.0.0:8080' }
  end
end
