# sshd_service = os[:family] == 'redhat' ? 'sshd' : 'ssh'

shared_examples 'kibana' do
  describe command('sv status kibana') do
    its(:stdout) { should match 'run: kibana' }
  end
  describe file('/opt/kibana/kibana-4.1.1/config/kibana.yml') do
    it { should be_file }
    its(:content) { should match '# This file was generated by Chef' }
  end
end
