shared_examples 'logstash' do
  describe command('sv status logstash') do
    its(:stdout) { should match 'run: logstash' }
  end

  describe file('/etc/service/logstash/env/LS_USER') do
    it { should be_file }
    its(:content) { should match 'kibana' }  # <= not a typo; testing hash merge
  end

  describe file('/etc/service/logstash/env/HELLO') do
    it { should be_file }
    its(:content) { should match 'WORLD' }
  end

  describe file('/opt/logstash/logstash-1.5.3/config/logging.yml') do
    it { should be_file }
    its(:content) { should match '# This file was generated by ELKTEST' }
  end

  describe file('/opt/logstash/logstash-1.5.3/config/logstash.conf') do
    it { should be_file }
    its(:content) { should match '# This file was generated by merged hash from a recipe!' }
  end
end
