# sshd_service = os[:family] == 'redhat' ? 'sshd' : 'ssh'

shared_examples 'logstash' do
  describe command('sv status logstash') do
    its(:stdout) { should match 'run: logstash' }
  end
  
  describe file('/etc/service/logstash/env/LS_USER') do
    it { should be_file }
    its(:content) { should match 'logstash' }
  end

  describe file('/opt/logstash/logstash-1.5.3/config/logging.yml') do
    it { should be_file }
    its(:content) { should match '# This file was generated by Chef' }
  end

  describe file('/opt/logstash/logstash-1.5.3/config/logstash.conf') do
    it { should be_file }
    its(:content) { should match '# This file was generated by Chef' }
  end
end
