shared_examples 'logstash_forwarder' do
  describe command('sv status logstash-forwarder') do
    its(:stdout) { should match 'run: logstash-forwarder' }
  end

  describe file('/opt/logstash-forwarder/logstash-forwarder-0.4.0/logstash-forwarder.conf') do
    it { should be_file }
    its(:content) { should match '# This file was generated by Chef' }
  end
end
