shared_examples 'logstash' do
  describe command('sv status logstash') do
    its(:stdout) { should contain 'run: logstash' }
  end

  describe file('/etc/service/logstash/env/LS_USER') do
    it { should be_file }
    its(:content) { should contain 'kibana' } # <= not a typo; testing hash merge
  end

  describe file('/etc/service/logstash/env/HELLO') do
    it { should be_file }
    its(:content) { should contain 'WORLD' }
  end

  describe file('/opt/logstash/logstash-1.5.3/config/logging.yml') do
    it { should be_file }
    its(:content) { should contain '# This file was generated by ELKTEST' }
  end

  describe file('/opt/logstash/logstash-1.5.3/config/logstash.conf') do
    it { should be_file }
    its(:content) { should contain '# This file was generated by merged hash from a recipe!' }
  end

  #  describe file('/var/log/logstash/current') do
  #    it { should be_file }
  #    its(:content) { should contain 'detected_master' }
  #  end
end
