shared_examples 'logstash_forwarder' do
  describe command('sv status logstash-forwarder') do
    its(:stdout) { should contain 'run: logstash-forwarder' }
  end

  describe file('/opt/logstash-forwarder/logstash-forwarder-0.4.0/logstash-forwarder.conf') do
    it { should be_file }
    its(:content) { should contain '# This file was generated by Chef' }
  end

  describe file('/var/log/logstash-forwarder/current') do
    it { should be_file }
    its(:content) { should contain 'Connected to' }
    its(:content) { should contain 'Registrar: processing' }
    its(:content) { should contain 'Launching harvester on new file:' }
  end
end
